import Link from "next/link";
import type { NoteSummary,PostSummary,ProjectSummary } from "@/lib/api";
export function ArrowIcon(){return <svg className="arrow-icon" viewBox="0 0 20 20" aria-hidden="true"><path d="M4 10h11M11 5l5 5-5 5"/></svg>}
export function PageHero({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children?:React.ReactNode}){return <section className="page-hero"><div className="container"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="hero-description">{description}</p>{children}</div></section>}
export function SectionHeading({eyebrow,title,href,linkLabel="查看全部"}:{eyebrow?:string;title:string;href?:string;linkLabel?:string}){return <div className="section-heading"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2></div>{href&&<Link className="text-link" href={href}>{linkLabel}<ArrowIcon/></Link>}</div>}
export function Tags({tags}:{tags:string[]}){return <div className="tag-row">{tags.filter(Boolean).map(tag=><Link className="tag" href={`/blog?tag=${encodeURIComponent(tag)}`} key={tag}>#{tag}</Link>)}</div>}
export function formatDate(value?:string){if(!value)return "持续更新";return new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"short",day:"numeric"}).format(new Date(value))}
export function PostCard({post,featured=false}:{post:PostSummary;featured?:boolean}){return <article className={`content-card post-card ${featured?"featured-card":""}`}>{post.coverImageUrl&&<Link className="post-card-cover" href={`/blog/${post.slug}`}><img src={post.coverImageUrl} alt={post.title}/></Link>}<div className="card-topline"><span>{post.series||"技术文章"}</span><time>{formatDate(post.publishedAt||post.updatedAt)}</time></div><h3><Link href={`/blog/${post.slug}`}>{post.title}</Link></h3><p>{post.summary||"这篇文章还没有摘要，点击查看完整内容。"}</p><div className="card-footer"><Tags tags={post.tags||[]}/><Link className="round-arrow" href={`/blog/${post.slug}`} aria-label={`阅读 ${post.title}`}><ArrowIcon/></Link></div></article>}
export function NoteCard({note}:{note:NoteSummary}){return <article className="content-card note-card"><div className="note-icon">{(note.category||"N").slice(0,1).toUpperCase()}</div><div className="note-body"><div className="card-topline"><span>{note.category||"未分类"}</span><time>{formatDate(note.updatedAt)}</time></div><h3><Link href={`/notes/${note.slug}`} prefetch={false}>{note.title}</Link></h3><p>{note.summary||"一条正在持续完善的技术笔记。"}</p><Tags tags={note.tags||[]}/></div></article>}
function techList(value?:string){return(value||"").split(",").map(item=>item.trim()).filter(Boolean)}
export function ProjectCard({project}:{project:ProjectSummary}){const statusMap:Record<string,string>={ACTIVE:"开发中",COMPLETED:"已完成",MAINTAINED:"维护中",EXPERIMENTAL:"实验性",ARCHIVED:"已归档"};return <article className="content-card project-card"><div className="project-visual">{project.imageUrl?<img className="project-image" src={project.imageUrl} alt={project.name}/>:<span className="project-monogram">{project.name.slice(0,2).toUpperCase()}</span>}<span className="project-status">{statusMap[project.status]||project.status}</span></div><div className="project-body"><h3><Link href={`/projects/${project.slug}`}>{project.name}</Link></h3><p>{project.summary||"一个值得记录的技术项目。"}</p><div className="tech-row">{techList(project.techStack).slice(0,5).map(tech=><span key={tech}>{tech}</span>)}</div><div className="project-links"><Link href={`/projects/${project.slug}`}>项目详情 <ArrowIcon/></Link>{project.repoUrl&&<a href={project.repoUrl} target="_blank" rel="noreferrer">源代码 ↗</a>}{project.demoUrl&&<a href={project.demoUrl} target="_blank" rel="noreferrer">在线演示 ↗</a>}</div></div></article>}
export function EmptyState({title="暂时没有内容",description="内容正在整理中，稍后再来看看吧。"}:{title?:string;description?:string}){return <div className="empty-state"><span>⌁</span><h3>{title}</h3><p>{description}</p></div>}
